CREATE DATABASE pegajosoDB;
USE pegajosoDB;

-- CREACIÓN TABLA TIPOS DE COMIDA
CREATE TABLE tipos(
id_tipos INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
tipo VARCHAR(40) UNIQUE KEY NOT NULL
);
-- CREACIÓN TABLA MENU DE PLATILLOS
CREATE TABLE menu(
id_menu INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
producto VARCHAR(40) UNIQUE KEY NOT NULL,
informacion VARCHAR(200) NOT NULL,
precio FLOAT NOT NULL,
tipo INT NOT NULL,
estatus TINYINT NOT NULL,
FOREIGN KEY (tipo) REFERENCES tipos(id_tipos)
);
-- CREACIÓN TABLA SUCURSALES
CREATE TABLE sucursales(
id_sucursales INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) UNIQUE KEY NOT NULL,
direccion VARCHAR(100) NOT NULL,
telefono VARCHAR(20) NOT NULL,
horario VARCHAR(50) NOT NULL,
estatus TINYINT NOT NULL
);
-- CREACIÓN TABLA FORÁNEA SUCURSALES_MENU
CREATE TABLE sucursales_menu(
id_sm INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
idmenu INT NOT NULL,
idsucursales INT NOT NULL,
estatus TINYINT NOT NULL,
FOREIGN KEY (idsucursales) REFERENCES sucursales(id_sucursales),
FOREIGN KEY (idmenu) REFERENCES menu(id_menu)
);
-- CREACIÓN TABLA BITACORA DE SEGUIMIENTO
CREATE TABLE bitacora(
id_bitacora INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
tabla VARCHAR(40) NOT NULL,
evento VARCHAR(100) NOT NULL,
usuario VARCHAR(40) NOT NULL,
fecha DATETIME
);
-- CREACIÓN TABLA DE ROLES
CREATE TABLE roles(
id_roles INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
rol VARCHAR(50) NOT NULL UNIQUE KEY
);
-- CREACIÓN TABLA DE USUARIOS
CREATE TABLE usuarios(
id_usuarios INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
email VARCHAR(45) NOT NULL,
passwd BLOB NOT NULL,
rol_id INT NOT NULL,
FOREIGN KEY (rol_id) REFERENCES roles(id_roles)
);
 